### ISSUE TITLE
Docs: Add permissions needed to run the action to README

### ISSUE THREAD

**Issue by stevenengland** [danielchabr/pr-has-one-of-labels#10]
Hi,

if a repo uses a resticted access it is neccessary to explicitely add permissions to use this action. Reading the code and from a first try on a private repo I guess in your case it is:

```
  pr_label_check:
    name: Check that the PR is labled.
    permissions:
      pull-requests: read
      checks: write
  ...
```
Can you confirm that and add it to the readme?
